version: '3'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./tmp_db/db:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/app
